---
- name: "Chocolatey"
  hosts: all
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present
          #remove public source
    - name: Disable Community Repo
      win_chocolatey_source:
          name: chocolatey
          state: absent
