---
- name: Ping 
  hosts: all 

  tasks:
  - name: ping
    win_ping:

  - name: disable print spooler
    win_service:
      name: spooler
      state: stopped
      start_mode: disabled
      
  - name: install all security updates
    win_updates:
      category_names:
        - SecurityUpdates
