---
- name: Ping 
  hosts: all 

  tasks:
  - name: ping
    win_ping:

  - name: disable print spooler
    win_service:
      name: spooler
      state: stopped
      start_mode: disabled
